### ISSUE TITLE
Multiline yaml looks ugly

### ISSUE THREAD

**Issue by xoxys** [thegeeklab/ansible-doctor#3]
Some multiline yaml values looks malformed in generated doc:

```YAML
freshrss_open_ports:
  - name: allow_freshrss_web
    rules: "-A INPUT -m state --state NEW -p tcp --dport {{ freshrss_exposed_port\
      \ }} -j ACCEPT\n"
    state: present

```
