### ISSUE TITLE
Code blocks in Meta descriptions get modified

### ISSUE THREAD

**Issue by wlitke** [thegeeklab/ansible-doctor#507]
If meta descriptions contain code blocks the contained code gets modified: Indentation (done with spaces) is removed and quotes (single and double quotes) are converted to HTML code (see below example). This makes the generated content hard to read and understand.

### Comment
~~~
# @meta description: >
# This is a test description with an usage example. There's an interesting result.
# 
# ```yaml
# - name: My to be included role
#   ansible.builtin.include_role:
#     name: namespace.collection.role_name
#   vars:
#     first_var: "test-value"
#     second_var: '1234567890'
# ```
# @end
~~~

### Result
~~~
This is a test description with an usage example. There&#39;s an interesting result.

```yaml
- name: My to be included role
ansible.builtin.include_role:
name: namespace.collection.role_name
vars:
first_var: &#34;test-value&#34;
second_var: &#39;1234567890&#39;
```
~~~
