### ISSUE TITLE
questions regarding parsing of requirements and dict variables

### ISSUE THREAD

**Issue by psych0d0g** [thegeeklab/ansible-doctor#589]
i would try to create a custom template to get requirement roles documented in the readme.md aswell, 
ansible galaxy works using a requirements.yml in the meta folder of a role with the following syntax:
```
- src: git+git@gitlab.xxx.net:package-roles/package.git
  version: main
- src: git+git@gitlab.xxx.net:package-roles/firewall.git
  version: main
- src: git+git@gitlab.xxx.net:package-roles/php.git
  version: main
```

any idea how one could archive that?

another question revolves around dictionary variables, and how to properly get doctor to detect them and document them.
currently its just this:
```
# @var apache2_listen_ports:type: dictionary
# @var apache2_listen_ports:description: >
# if the https port is omitted, the default vhost will only listen on http
# otherwise a redirect is included in the vhost that redirects http requests to https
# @end
apache2_listen_ports:
  http: 80
  https: 443
```
and doctor itself would also only detect the initial dict var, is there a way to have it split them out, and detect and document the keys in the dict as vars aswell?
