### ISSUE TITLE
Module tags are showing under Discoved tags in Readme.md file

### ISSUE THREAD

**Issue by aradhanas9** [thegeeklab/ansible-doctor#594]
When generating the README.md file using ansible-doctor, its auto discovering feature is detecting ansible module tags which is then appearing under "Discovered tags," despite the documentation stating that the task tags should be displayed under "Discovered tags" heading. 
Please confirm if this is the expected behavior. Also please confirm if there is any way to skip auto-detection of ansible module tags.

**Comment by xoxys** [comment]
Please give an example of what you mean with "ansible module tags".

**Comment by aradhanas9** [comment]
Thank you for your prompt response.
Please find an example below:
I've created an aws role for vpc creation and when running ansible-doctor for same, tags for amazon.aws.ec2_vpc_net module is getting discovered under Discovered Tags in README.md file.
Role snippet:
```
- name: Create VPCs
  amazon.aws.ec2_vpc_net:
    region: "{{ region }}"
    name: "{{ vpc.name }}_{{ region }}"
    cidr_block: "{{ vpc.cidr }}"
    debug_botocore_endpoint_logs: "{{ vpc.debug_botocore_endpoint_logs | default(false) }}"
    ... some code...
    tags: "{{ custom_tags }}"
```
README.md file, Discovered Tag content
```
## Discovered Tags

**_{{ custom_tags }}_**
```

**Comment by xoxys** [comment]
I'm a bit confused. If that is a "module tag" (for me this is a task in a role and tags added to tasks are "task tags") what is an example for a "task tags" in your case?

**Comment by xoxys** [comment]
From my perspective, this is the expected behavior. All `tags:` attributes as described in the [ansible docs](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html#adding-tags-with-the-tags-keyword) added to the tasks of a role by the role author will be discovered and added to the `Discovered Tags` section. 

As tasks can be used by the role user together with `--limit` in play runs, they should be always documented. Therefor, there is no option to disable the tag discovery.

**Comment by aradhanas9** [comment]
> I'm a bit confused. If that is a "module tag" (for me this is a task in a role and tags added to tasks are "task tags") what is an example for a "task tags" in your case?

Thanks for your guidance.
Please refer below code snippet showing task tags and module tags/
```
- name: Create VPCs
  amazon.aws.ec2_vpc_net:
    region: "{{ region }}"
    name: "{{ vpc.name }}_{{ region }}"
    cidr_block: "{{ vpc.cidr }}"
    debug_botocore_endpoint_logs: "{{ vpc.debug_botocore_endpoint_logs | default(false) }}"
    ... some code...
    tags: "{{ module_tags }}" 
  tags: "{{ task_tags }}" 
```
