### ISSUE TITLE
Pre-commit hook is not working fine.

### ISSUE THREAD

**Issue by aradhanas9** [thegeeklab/ansible-doctor#599]
Hi,
I am trying to use ansible-doctor pre-commit hook but getting error as below:
```
aradhana.saxena@DEL1-LHP-N82532:~/pre-hook-testing/devops$ git commit -m "testung"
ansible-doctor...........................................................Failed
- hook id: ansible-doctor
- exit code: 1

[CRITICAL] No Ansible role detected
```
Steps followed:
I have added .pre-commit-config.yaml file to the root of my repository but when I am running the commit, I am getting above error.
**Content of .pre-commit-config.yaml**
```
aradhana.saxena@DEL1-LHP-N82532:~/pre-hook-testing/devops$ cat .pre-commit-config.yaml 
---
repos:
  - repo: https://github.com/thegeeklab/ansible-doctor
  # change ref to the latest release from https://github.com/thegeeklab/ansible-doctor/releases
    rev: v3.1.2
    hooks:
      - id: ansible-doctor
```
It seems ansible-doctor is unable to find the role. My directory structure is as follows:
```
.
├── inventory
│   ├── group_vars
│   │   ├── abx.yaml
│   │   └── abz.yaml
│   ├── host_vars
│   │   ├── abc.yaml
│   │   ├── xyz.yaml
│   ├── inventory.aws_ec2.yml
│   └── static_inventory.yml
├── playbooks
│   ├── deploy-configuration.yaml
│   ├── deploy-infra.yaml
│   └── roles
│       ├── basic_configuration
│       │   ├── meta
│       │   │   └── main.yml
│       │   ├── README.md
│       │   └── tasks
│       │       └── main.yml
│       ├── ec2
│       │   ├── meta
│       │   │   └── main.yml
│       │   ├── README.md
│       │   └── tasks
│       │       └── main.yml
│       ├── rds
│       │   ├── defaults
│       │   │   └── main.yaml
│       │   ├── meta
│       │   │   ├── argument_specs.yml
│       │   │   └── main.yml
│       │   ├── README.md
│       │   └── tasks
│       │       └── main.yml
│       ├── s3
│       │   ├── defaults
│       │   │   └── main.yaml
│       │   ├── meta
│       │   │   └── main.yml
│       │   ├── README.md
│       │   └── tasks
│       │       └── main.yml
│       ├── system_configuration
│       │   ├── defaults
│       │   │   └── main.yaml
│       │   ├── meta
│       │   │   └── main.yml
│       │   ├── README.md
│       │   └── tasks
│       │       └── main.yml
│       └── vpc_subnet
│           ├── defaults
│           │   └── main.yml
│           ├── meta
│           │   └── main.yml
│           ├── README.md
│           └── tasks
│               ├── alb.yml
│               └── main.yml
├── .pre-commit-config.yaml
├── README.md
└── requirements.txt
```
Please guide how to resolve this error.
