### ISSUE TITLE
Tag skipping not working

### ISSUE THREAD

**Issue by xoxys** [thegeeklab/ansible-doctor#710]
I'm sorry to comment this issue, but it appear to be not helping.

I'm trying this following `ansibledoctor.yml` configuration:
```yaml
---
logging:
  level: warning
force_overwrite: true
exclude_tags:
  - always
  - never
```

And `never` tag still appear in autodiscovery tags section.

And i think I'm not the only one.
I even found this roles README with a `ansibledoctor.yml` configuration with `exclude_tags` where the mentionned tag appear in README (always)
https://github.com/oravirt/ansible-oracle/tree/master/roles/oraswgi_install

I also tried with an environment variable without succes : 
```sh
EXCLUDE_TAGS=["never"] ansible-doctor
```

_Originally posted by @marcpaulchand in https://github.com/thegeeklab/ansible-doctor/issues/286#issuecomment-2150961778_
