### ISSUE TITLE
pre-commit setup git repo with multiple roles

### ISSUE THREAD

**Issue by davidre** [thegeeklab/ansible-doctor#889]
Hi,

thanks for your previous answer (https://github.com/thegeeklab/ansible-doctor/issues/878) 

It works for a single role now.

One last question about the pre-commit setup.
I have a single git repo for an ansible collection containing multiple roles.

```
❯ tree -L 2 -a
.
├── .git
├── .gitignore
├── .pre-commit-config.yaml
├── .python-version
├── README.md
├── hello.py
├── pyproject.toml
├── roles
│   ├── documentation_generator
│   ├── fetch_pub_key
│   ├── gitlab_committer
│   └── trigger_cloud_pipeline
└── template_sync.yaml
```

Probably the pre-commit hook doesn't work for multiple roles because you can only specify one base directory. Or am I missing something?

```
-   repo: https://github.com/thegeeklab/ansible-doctor
    # update version with `pre-commit autoupdate`
    rev: v7.0.4
    hooks:
    -   id: ansible-doctor
        args:
          - roles/documentation_generator/
            #- roles/fetch_pub_key/
            #files: ^roles/[^/]+/(meta|defaults)/main\.yml$
```

Regards,
David
